version: '3.8'
services:
  mailswift:
    build: .
    command: sh -c "yarn install && yarn dev"
    ports:
      - "7500:8001"
    environment:
      MONGODB_URI: "mongodb://mongo_db:27017/mailswift"
    volumes:
      - .:/usr/src/mailswift
      - /usr/src/mailswift/node_modules
    depends_on:
      - mongo_db
  
  mongo_db:
    container_name: mongo_container
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: